version: "3.7"

services:

  sudoku:
    image: dmitriyvasil1986/sudoku_server:latest
    restart: always
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - APP_NAME=${APP_NAME}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - SECRET=${SECRET}
      - DEBUG=${DEBUG}
      - SALT=${SALT}
      - HOST=${HOST}
      - PORT=${PORT}
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./dbdata:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./static/:/static/
